<!doctype html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" href="./assets/logo/pioupiou_white.svg" />
    <meta name="description" content="Pioupiou, un réseau social comme les autres...">
    <meta name='robots' content='index,follow'>

    <link rel="stylesheet" href="assets/css/style.css" type="text/css" />
</head>

<body>
    <header>

    </header>
    <main>

        <?php include $template ?>
    </main>
    <footer>
    </footer>
    <script type="module" src="public/js/main.js"></script>
</body>

</html>